-- CYBERSENTINEL AI DATABASE SCHEMA
-- Intelligent Cyber Incident Response System
-- PostgreSQL Version


-- USERS TABLE

CREATE TABLE IF NOT EXISTS users (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name TEXT NOT NULL,

    email TEXT NOT NULL UNIQUE,

    password TEXT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);


-- INCIDENTS TABLE

CREATE TABLE IF NOT EXISTS incidents (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,

    incident_type TEXT NOT NULL,

    title TEXT NOT NULL,

    description TEXT NOT NULL,

    risk_score INTEGER NOT NULL DEFAULT 0,

    risk_level TEXT NOT NULL DEFAULT 'Low',

    impact TEXT,

    reason TEXT,

    response_recommendation TEXT,

    prevention_tips TEXT,

    status TEXT NOT NULL DEFAULT 'Open',

    evidence_path TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_incidents_user

        FOREIGN KEY (user_id)

        REFERENCES users(id)

        ON DELETE CASCADE

);


-- REPORTS TABLE

CREATE TABLE IF NOT EXISTS reports (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,

    incident_id INTEGER NOT NULL,

    report_path TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reports_user

        FOREIGN KEY (user_id)

        REFERENCES users(id)

        ON DELETE CASCADE,

    CONSTRAINT fk_reports_incident

        FOREIGN KEY (incident_id)

        REFERENCES incidents(id)

        ON DELETE CASCADE

);


-- INDEXES

-- Fast user lookup by email

CREATE INDEX IF NOT EXISTS idx_users_email

ON users(email);


-- Fast incident lookup by user

CREATE INDEX IF NOT EXISTS idx_incidents_user_id

ON incidents(user_id);


-- Fast incident lookup by risk level

CREATE INDEX IF NOT EXISTS idx_incidents_risk_level

ON incidents(risk_level);


-- Fast incident lookup by status

CREATE INDEX IF NOT EXISTS idx_incidents_status

ON incidents(status);


-- Fast report lookup by user

CREATE INDEX IF NOT EXISTS idx_reports_user_id

ON reports(user_id);


-- Fast report lookup by incident

CREATE INDEX IF NOT EXISTS idx_reports_incident_id

ON reports(incident_id);
